mozilla/multi-account-containers

webextension/css/popup.css, webextension/js/popup.js, webextension/popup.html
Does what it says on the branch name ...
=> newtab icon to open new container tab from pop-up

webextension/css/popup.css, webextension/js/popup.js, webextension/popup.html
This is my first commit. It's just an experiment to understand the development workflow.
I guess this patch will be reviewed by someone, and then merged.
Let's see what happens :)
=> Title and cursor attributes in popup UI

webextension/js/popup.js
I also converted some "const" to "let" and some "foo=>" to "foo => "
=> Let's use a DocumentFragment instead innerHTML

package.json
Sorry, also ran [**fixpack**](http://npm.im/fixpack) to make everything beautifully A-z sorted, which causes a bit of diff-churn.
=> Add repo and fix SPDX license in package.json

data/chrome.css, index.js
This implements the same style as mentioned in the email, follow up work should be done to make it have the same style as #13
=> Initial tab restyle work to match experiment bug #13

.eslintrc.js, index.js, webextension/js/popup.js
=> eslint updated

index.js, webextension/css/popup.css, webextension/js/popup.js, webextension/popup.html
The UI is not completed but the logic and all the API between child and parent process is done.
=> Container tab listing

.gitignore, index.js, webextension/css/popup.css, webextension/img/container-newtab.svg, webextension/js/popup.js, webextension/popup.html
Latest UI updates to match [Panels Spec](https://www.dropbox.com/sh/jczak1kfm80q334/AAAvoNwz5lrcPZn1rreRD1E_a)
=> WIP for #55

.eslintrc.js, package.json
=> Add ESLint promise plugin

.jpmignore, package.json, webextension/background.js
=> Add .jpmignore file

webextension/js/popup.js
=> Correct remove method for tabs #145

package.json, webextension/manifest.json
Just bumping version so I can get a freshly-signed `.xpi` file for testing and review.
=> version bump to 0.0.2 for fresh signing

index.js
I'm sure this isn't the right/best way to do this(?) - using `Ci.nsICookieManager2` directly, but we need to get these MVP bugs fixed.
@bakulf @jonathanKingston - what do you think?
=> fix #174: remove add-on containers on uninstall

index.js
=> Banking to Finance

data/usercontext.css, index.js
A bit of a hack but, 
Fixes #150 
NB, this was done on top of #216 b/c it touches the same file
=> Custom tab rendering fix

data/usercontext.css
=> tidy up tab dropdown menupanels

index.js
=> fix linter errors

webextension/css/popup.css
=> Fixing accessibility of edit containers radio buttons. Fixes #223

.stylelintrc, package.json
Rebase of https://github.com/mozilla/testpilot-containers/pull/251
=> Update stylelint rules. Fixes #230

.gitignore, bin/build-addon.sh, package.json, webextension/manifest.json
@clouserw does this look good?
=> fix #162: bin/build-addon.sh automates txp deploys

data/usercontext.css, docs/metrics.md, index.js, package.json, webextension/css/popup.css, webextension/js/popup.js, webextension/manifest.json, webextension/popup.html
Fixes for #240, #242, #257, #258, #272.
=> Merge 1.0 into production branch to publish signed .xpi

webextension/js/popup.js
See https://github.com/mozilla/testpilot-containers/pull/358/commits/6b995586fdc25b146bd46470fe74c38a37d24347#r105438084
=> bind submitForm event listener to keep _editForm

index.js, webextension/background.js, webextension/js/confirm-page.js, webextension/js/popup.js, webextension/manifest.json
supersedes #479 which supersedes #471 
... superception
The logic has been moved into the background script which should last even if the window is closed.
Notice the comment on 628 of webextension/js/popup.js: https://github.com/mozilla/testpilot-containers/compare/master...jonathanKingston:remove-sdk#diff-0effdbf34829f2ab5dac6ed4d8906066R628 basically the response from the background is ignored as the window that has the popup in it gets removed.
=> Remove sdk

.eslintrc.js, package.json, webextension/js/popup.js
I deprecated my extension in favour of the new https://github.com/mozilla/eslint-plugin-no-unsanitized this is based on a colab of mine and freddies rules.
=> Move to the Mozilla backed no-unsanitized ESLint plugin

webextension/css/popup.css, webextension/js/popup.js, webextension/manifest.json, webextension/popup.html
I think the command shortcut only works in nightly currently. It also doesn't seem to make the document active either which means it requires two tabs to get into the doorhanger which isn't the best. I tried focusing an element when the page became visible but nothing seems to work in that department.
=> Adding in shortcut and keyboard controls

index.js, webextension/background.js, webextension/js/popup.js
Backing this up... super buggy at the moment. Adding PR for visibility only.
=> Interim WIP patch of more removal

.eslintrc.js, webextension/background.js, webextension/confirm-page.html, webextension/css/content.css, webextension/css/popup.css, webextension/js/confirm-page.js, webextension/js/content-script.js, webextension/js/popup.js, webextension/js/utils.js, webextension/manifest.json, webextension/popup.html
Supersedes:
#542
#547
#560
#565
=> Shield study work

webextension/js/confirm-page.js
=> Fix reload telemetry payload.

docs/metrics.md
We can add more commits to this branch if/as we finish our Telemetry reliability audit for shield. (#588)
=> document "alltabs-menu" as an open tab source

webextension/js/background/backgroundLogic.js
Apparently I didn't make a PR for this yesterday.
=> Fix moving of more than one tab to a new window. Fixes #746

install.rdf, package.json, webextension/manifest.json
r? but we can wait to merge this until others are merged.
=> for #665: update title, desc, version for AMO

install.rdf, package.json, webextension/manifest.json
Already made a tag of this; just need to merge it to master too.
=> bump version to 4 for AMO

webextension/js/popup.js
Cleared up the legacy storage stuff that was sat in localStorage, it's pretty safe to say users have had this update based on the numbers (this update was back in july).
=> Store only one of the current version opened. Fixes #833

src/js/background/assignManager.js
siteSettings can be null, with this change we can avoid an exception.
=> Fix for siteSettings is null

.gitignore, .travis.yml, README.md, package.json, src/js/background/assignManager.js, src/js/background/messageHandler.js, src/manifest.json, src/popup.html, test/.eslintrc.js, test/browser.mock.js, test/features/assignment.test.js, test/features/external-webextensions.test.js, test/helper.js, test/issues/940.test.js, test/setup.js
@groovecoder tested locally, seems fine to me. Would like another testing of this.
Untested so far is the cross extension comms.
=> Version 6.0.0

src/js/background/assignManager.js, src/js/background/messageHandler.js
Counterpart commit: https://github.com/mozilla/contain-facebook/pull/127
=> Handle jailed domains

src/js/popup.js
- Resolves the issue of container tab can wrongly be moved to a new window even if it's the only opened tab.
=> #885 disables move tab to a new window when only one tab is opened

package.json, src/js/background/backgroundLogic.js, src/js/popup.js, src/popup.html
Supersedes https://github.com/mozilla/multi-account-containers/pull/1205 with updated `package.json` `devDependencies` to fix Travis.
=> Fix delete warning message #1051 

package.json, src/manifest.json
=> Fixes #1328: Adding new version 

CODE_OF_CONDUCT.md
https://github.com/mozilla/multi-account-containers/issues/1364
=> Bring CODE_OF_CONDUCT.md current

src/js/popup.js
#outreachy applicant fixes #1507 
@maxxcrawford @groovecoder this PR closes #1507 and any feedback will be greatly appreciated! 
I had all tests (run using `npm test`) passing locally.
=> remove HTML entities from tooltip

src/css/popup.css, src/popup.html
Supersedes https://github.com/mozilla/multi-account-containers/pull/1545 with squashing & rebasing on master.
=> fix odd edit arrow alignment

src/js/background/assignManager.js, src/js/background/messageHandler.js, src/js/options.js, src/options.html, test/browser.mock.js
Suggested updates after merge from PR #1537 @Rob--W and @groovecoder 
Fix for #1564
=> fixed #1564: cleanup updates requested for bookmark context menu

package.json, src/js/popup.js, src/manifest.json
=> Made selector for keyboard shortcuts more specific to fix #1666

package.json, src/manifest.json
Because I accidentally already made `6.2.4` tag.
=> bump version to 6.2.5

.stylelintrc, package.json, src/css/options.css, src/css/popup.css, src/img/container-delete.svg, src/manifest.json, src/options.html
- Issue #1746
Wrapping fix: 
Hover state:
Settings page (Light OS theme): 
Settings page (Dark OS theme):
=> UX/UI Followup Issues

package.json, src/manifest.json
=> Update version number for new release

README.md
Let's open this to everyone and not assume any specific language or country.
AMO will automatically redirect to user's language and country.
=> Improve accessibility by adjusting AMO links

package.json, src/manifest.json
Compare: https://github.com/mozilla/multi-account-containers/compare/7.3.0...master
=> Update version number to 7.4.0

package.json, src/manifest.json
=> Bump version number to 8.0.6

src/css/popup.css, src/js/options.js, src/js/pageAction.js, src/js/popup.js, src/js/utils.js, src/options.html, src/popup.html
This patch add a new preference in the option page to let the user select a light/dark theme. It also auto-detect the OS theme if it's set to `auto`.
=> fix #1948 Add option to select a light/dark theme

.github/ISSUE_TEMPLATE/config.yml
- Remove en-US in SUMO URLs so it redirects the user to right locales
- Make it clearer that Ask a question is about support questions
=> Update issue menu

CONTRIBUTING.md
Found a typo on the contribution doc, so making this huge PR to remedy it. 😆
=> fix git submodule command doc

package.json
This removes all the critical and high vulnerabilities
Fixes #2395 
Fixes #2394
=> Update minimal version of web-ext

src/css/options.css, src/js/background/backgroundLogic.js, src/js/background/sync.js, src/js/options.js, src/options.html, test/features/sync.test.js
We won't be able to have a fix for https://github.com/mozilla/multi-account-containers/issues/2439 before 8.1.0 is released so we need to backout https://github.com/mozilla/multi-account-containers/pull/2231 and https://github.com/mozilla/multi-account-containers/pull/2383.
=> Backout #2231 from 8.1.0

package-lock.json, package.json, src/manifest.json
These changes are in the release branch but not in main yet.
=> Release changes back to main

src/img/multiaccountcontainer-16.svg
To work around https://bugzil.la/1883166.
*Please include a summary of the changes including relevant motivation and context.*
=> Explicitly specify width and height in SVG icon.

package.json, src/manifest.json
Upgrades the add-on version from 8.1.3 to ~~8.1.4~~ 8.2.0
=> Version upgrade

CONTRIBUTING.md, README.md
Update CONTRIBUTING.md to include tips for contributing and remove Discourse link and replace it with GH discussions board from README.md
=> Community documentation update

src/js/background/backgroundLogic.js
Fixes #2746
Firefox 137 introduced tab groups. Tab group web extension support is rolling out in Firefox 138 and later. Tab movements, like the movements done when sorting tabs by container, can inadvertently add or remove tabs from tab groups.
In order to keep users' tab groups intact, this patch only sorts tabs outside of tab groups. Due to the lack of the tabGroups web extensions API as of Firefox 138, this patch cannot move tab groups, so all ungrouped tabs move to the end of the tab strip. That means after sorting, all tab groups will move to the beginning of the tab strip.
* #2746
=> Fix #2746: sort only ungrouped tabs

src/js/background/assignManager.js, test/common.js
Fixes https://github.com/mozilla/multi-account-containers/issues/2735
=> Avoid logspam: "Cannot find menu item with id ..."

src/css/popup.css, src/js/popup.js, src/popup.html
People don't seem to be too happy with that popup and consider this an AD. So let's remove it :) 
Got approval from the with the VPN PM, that this should go. 
* Fixes https://github.com/mozilla/multi-account-containers/issues/2589
=> Remove the Mozilla-VPN Banner Ad
