mozilla/multi-account-containers

package.json
Noticed we added a devDep for addons-linter, but it wasn't wired to anything.
Now running `npm run lint` will run both ESLint and the addons-linter tools.
If you want to run the scripts individually, you can still use stuff like `$ npm run lint:js -- --fix` to autofix any ESLint errors/warnings.
=> Tweak package.json lint script to lint add-on

.eslintrc.js, index.js, test/test-index.js, webextension/js/popup.js
Not 100% on the `prefer-const` rule, since I think [Firefox has a bug (1094995)](https://bugzilla.mozilla.org/show_bug.cgi?id=1094995) with `const` and `for..of` loops, so when using `for..of`, I had to inline disable that rule for that line.
For more information, see https://github.com/eslint/eslint/issues/3104
=> Add ESLint no-var and prefer-const rules

webextension/css/popup.css, webextension/img/container-arrow.svg, webextension/js/popup.js, webextension/popup.html
Fixes (so far) as close to the mockups from #94 as I can make it:
* Text margin added to the "Remove this Container?" confirm panel
* Text size, wrapping, and overflow cleaned up in "Currently opened tabs" panel
* Back and forward arrows changed to an actual arrow svg image
=> for #94, for #95: more ui updates

webextension/css/popup.css, webextension/js/popup.js
=> fix #142: disable arrow if container has no tabs

webextension/css/popup.css, webextension/js/popup.js, webextension/popup.html
=> fix #141: container-name class truncate long names

webextension/css/popup.css
This should be checked on other platforms other than Linux. I really don't like the solution used however I don't know of anything that would work as image replacement hacks don't work and hiding the inputs makes the accessibility benefits of using radio's go away.
=> Fixing issues for edit screen on Linux. Fixes #157

data/usercontext.css
@kjozwiak @jonathanKingston I made the command decision to get rid of the full-width tab color thing since it's a nightmare. This accounts for the following:
- normal tabs
- pinned tabs
- dev edition
- tab center
I did all of this on FF for MacOS so it might be good to give it a look on linux/windows
=> fix tab css

index.js, webextension/css/popup.css, webextension/js/popup.js
I dislike almost everything about this patch/PR, but we want to disable the move feature when we detect incompatible add-ons. There's a hover tooltip, but [bug 1269421](https://bugzilla.mozilla.org/show_bug.cgi?id=1269421) means I had to also add a message in the pop-up itself ...
To verify/test ...
1. Install Pulse (or PageShot) addons (via Test Pilot add-on or manually)
2. Install Containers addon
3. Create a container tab
4. Open the "container tabs" panel
5. [ ] Verify "Move tabs" is disabled with an appropriate message
6. Un-install or disable pulse (or PageShot) addon(s)
7. Open the "container tabs" panel again
8. [ ] Verify "Move tabs" is re-enabled
=> for #242: disable move when incompatible add-ons detected

docs/metrics.md, index.js
This adds a Telemetry ping when users encounter the "Incompatible addons" message in the containers pop-up. The ping is sent with `uuid` so we will be able to group the pings to know *how many users* are seeing the message - not just the raw counts of how many times it's shown.
To verify:
1. Install Test Pilot add-on (required to create Telemetry channel)
2. Install Pulse (or PageShot) experiment(s)
3. Install Containers experiment
4. Open a container tab
5. Open the pageAction popup
6. Click the container
7. [ ] Verify you see the "incompatible with experiments" message on the disabled move action
8. Go to `about:telemetry`, "Archived ping data" ...
=> fix #272: add event telemetry for incompat addons

data/usercontext.css
As stated by @fvsch on #354, **Containers** doesn't need the **Tab Center** centric CSS to have compatibility. The PR is simply to remove the segment to move along the compatibility.
=> Removing tabcenter css

index.js, package.json, webextension/background.js, webextension/confirm-page.html, webextension/css/confirm-page.css, webextension/css/popup.css, webextension/js/confirm-page.js, webextension/manifest.json
Super WIP PR just to demo the functionality for @johngruen and @groovecoder ...
STR (Assumes default search is google):
1. create Google container
2. add a new google container tab
3. go to google.com
4. right click, "Always open in this container"
5. open a new non container tab
6. Search string "test"
Tab created in step 6. Will be in "Google" container.
Loads of polish needed like:
- Change context menu when already auto linking.
- Show warning for paranoid users like myself on autolinking
- Allow container based auto dismissal of paranoid warning
- Potentially show URL autolinking in other menus
=> WIP of auto-container-origin

docs/metrics.md, webextension/background.js, webextension/manifest.json
Adds a new `page-requests-completed-per-activity` event ping with `pageRequestCount` metric. Note: these pings are in addition to the `-per-tab` pings, so we will analyze them separately.
Steps to verify:
* Create some (non-container and/or container) tabs
* Make some page loads in some of the tabs
* Leave your computer idle for ~60s (don't close any of the tabs)
* Go to about:telemetry
* Check "archived ping data"
* The payload drop down should contain "*-testpilottest" options - pick some
* Verify they have the expected `page-requests-completed-per-activity` event string, and the proper `userContextId` and `pageRequestCount` values
* Make some more page loads in the still-open tabs
* Go to about:telemetry
* Check "archived ping data"
* The payload drop down should contain …
=> for #321: page count telemetry per activity

webextension/css/content.css, webextension/js/content-script.js, webextension/manifest.json
This likely won't solve all layout issues that we find. Loading it earlier prevents it from not being shown at all on page load.
Looks like we just need to override every property that the page might get, which is a long list. I fixed all the examples to all look the same.
We can review better post release.
=> Fix different display in content warning notice. Fixes #630

study.js
=> add surveyUrl for shield study participants

index.js, package.json, webextension/manifest.json
@groovecoder let me know when this is merged and I can rebase it into my other patch (I would like to land that this week, I still can't replicate on Nightly at leasr the issue you had).
=> Fix on update icons being reset to central defaults. Fixes #703

install.rdf, package.json, webextension/manifest.json
Merge 3.1.1 with deleted `updateURL`. This should push any remaining Test Pilot 3.x over to 4.x from AMO.
If it doesn't, we can try a 3.1.2 that explicitly sets the `updateURL` to an update manifest URL on AMO.
=> remove updateURL so Test Pilot users go to AMO

install.rdf, package.json, webextension/manifest.json
New version to release these bug-fixes:
c433c6b Clean up disabled Private Mode notice. Fixes #878
1c09c29 Fix assignment of stale containers. Fixes #803 Fixes #827
07711aa Preventing default on enter handler as it seems to call click handlers now. Fixes #856
16ed899 Change delete title to remove. Fixes #700
88e6dc7 Add strict min version and extension id and bump version to 4.0.2. Fixes #692. Fixes #852
77ba1b7 Store only one of the current version opened. Fixes #833
e84e482 Minor README edit
3ec81e3 Add launch notice in README
01a6288 Fix dumping UUID image into the page. Fixes #812
=> bump version to 4.0.3

webextension/js/popup.js
Makes it more effective to open the first ten containers in the
containers list. Keys 1-0 will open containers 1-10, if that container
exists.
Note: the plugin's popup panel does not autofocus when opened. This
requires the user to focus on the panel by either clicking or pressing
TAB before using shortcut keys. This behavior is consistent with the previous shortcuts for
this addon.
=> Adds shortcut to open containers.

webextension/js/background/assignManager.js
This mini changeset ensures that redirected tabs that have been opened in the background (with a middle click, for instance) don't steal the focus from the current tab. Particularly useful for opening up several top sites in a row from the New Tab page, each requiring a redirect.
Fixes #442, fixes #923.
=> Maintain the active state of the redirected tab

package.json, src/manifest.json
`manifest.json` needs `id: @testpilot-containers` to make sure it updates the existing 4.x legacy add-on instead of making a new one.
=> id:@testpilot-containers to manifest.json; 5.0.1

src/js/popup.js
Before opening a container with the `1-9` shortcut, it ensures that the current pannel is the "containersList"
=> Fixes #1084.

src/js/background/backgroundLogic.js
Create the new window with the default tab rather than an existing tab,
then pin the default tab. This allows any pinned tabs to be moved to the
new window because they're not allowed to be moved after a un-pinned
tab. The default tab is automatically closed later in `moveTabsToWindow`
because it's not a part of the container.
=> Fix #1053.

src/js/background/assignManager.js
Prevents potential redirects from opening two tabs. [Detailed explanation is here](https://github.com/mozilla/multi-account-containers/issues/940#issuecomment-364361409).
Added also [a test](https://github.com/stoically/multi-account-containers/blob/b6bcd99dc827d953912f80e19e05a508df58fe22/test/issues/940.test.js) to #1107 which you can see fail without this fix.
Affects #940 #1003 #1080 - but doesn't fully fix them. Fewer people should be affected by two tabs opening especially in combination with Add-ons that redirect.
=> Cancel requests with the same requestId

src/js/background/messageHandler.js, src/manifest.json
Hi,
thanks for your work on Multi-Account Containers!
I've developed an "[extra Add-on](https://github.com/mozilla/multi-account-containers/issues/929)" named Temporary Containers ([AMO](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers) / [GitHub](https://github.com/stoically/firefox-add-on-temporary-containers)) and in order to support some of the available features (e.g. automatically open clicked links in a Temporary Container) I have to rely on fuzzy logic to make a best guess about when MAC is going to reopen an URL in a Container or Confirm Page. This leads to random bugs where Tabs get closed or multiple Tabs get opened - up to the point that people [decide against using my Add-on](https://github.com/stoically/firefox-add-on-temporary-containers/issues/15#issuecom …
=> Allow webextensions with contextualIdentities permission to get assignments

.gitignore, src/js/background/assignManager.js
When reloading a tab in a container, we will now pass the openerTabId. This is primarly for https://github.com/piroor/treestyletab but also to pass more complete information when creating tabs.
Related to #1065   feature request] pass opener tab id when creating tabs in order to know the parent
=> Pass opener tab id when creating tabs in order to know the parent

.travis.yml, package.json, src/popup.html, test/.eslintrc.js, test/browser.mock.js, test/features/assignment.test.js, test/helper.js, test/issues/940.test.js, test/setup.js
Hi,
since jkt signaled on IRC that adding some tests to the codebase is OK, here's a proposal that loads `popup.html` and `background/index.html` with `jsdom` and executes a basic assignment feature test:
* [Initialize browser with example.com tab in firefox-container-1](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L2-L10)
* [Click the `container-page-assigned` checkbox to assign example.com to firefox-container-1](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L12-L16)
* [Open new example.com tab in firefox-default container](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab85 …
=> Adding assignment feature tests

test/browser.mock.js, test/features/assignment.test.js, test/features/external-webextensions.test.js
Thanks for merging the other PRs!
Here's a fix for the assignment feature test to cover the new openerTabId that gets passed in and a feature test for the external webextensions messaging.
=> Add and fix tests for 6.0.0

package.json, src/js/background/assignManager.js, test/browser.mock.js, test/helper.js, test/issues/940.test.js, test/setup.js
As mentioned in #1114 there are still cases where two tabs are opened when redirects are involved:
In this case `www.youtube.com` is assigned. The initial request goes to `http://youtube.com` which results in redirects to `https://youtube.com` and two times `https://www.youtube.com` - the last request has a different `requestId`. All have the same `tabId`.
To fix this all requestIds and urls that reach the point of being "reopened" are marked as canceled in relation to the tabId - or are canceled if already marked as canceled. Instead of cleaning up canceled requests with a timeout, we can use `webRequest.onCompleted` and `webRequest.onErrorOccurred` - though, since they are not 100% reliable, a 2seconds backup cleanup timer is included (uncanceling is also covered with tests).
The …
=> Cancel redirects for the same requestIds and urls if originating from the same tabId

src/js/popup.js
- Following the thread of the issue, I found the discussion is absolutely correct about the `focus()`
- After searching for hours the reason I found was interesting and weird; The solution was to "pause" the JavaScript execution to let the rendering threads catch up. And this is the effect that `setTimeout()` with a timeout of 0 does. For better understanding, you can refer this link [here](https://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful)
- For even better understanding, answer your curiosity by watching [this](https://www.youtube.com/watch?v=8aGhZQkoFbQ) 😄.
- The `select()` and `focus()` both work fine but `focus()` seems to be hidden by the input box-shadow.
=> #1028 resolves focus name field on opening new container sub-panel

package.json
Fixes #1261 
Removed deploy-txp as suggested by @groovecoder [here](https://github.com/mozilla/multi-account-containers/issues/1261#issuecomment-426376209).
Upgraded addons-linter and htmllint-cli
@groovecoder please review. Thanks :smile:
=> Fixes vulnerabilities in npm

src/css/popup.css, src/js/popup.js, src/popup.html
- Resolves the clickable `Edit Container` button even after no container is present.
=> #256 disables edit-container button when no container is present

src/js/background/backgroundLogic.js, src/js/background/messageHandler.js
Moving tabs to a new window for a hidden container was resulting in two of every tab being opened in a new container. 
This seemed to be happening because :- 
`moveTabsToWindow` has logic within it to show hidden tabs and does so by reading the `containerState`, getting the hidden tabs information, opening the hidden tabs and then writing back the new `containerState`. In addition, when a new tab is created, an event is fired to unhide the container using the `showTabs` method. `showTabs` too reads `containerState` (information about the hidden tabs) from the cookie. However, it seems like `showTabs` reads it before `moveTabsToWindow` finishes writing the updated state. `showTabs` too, therefore, proceeds to show all hidden tabs
This PR contains code that modifies each of those functions …
=> Fixes #1109 , rest of #791

src/js/background/assignManager.js
- Not sure if this is what we wanted, but it seems to work as far as I tested it.
=> exempting `always open in` functionality for non-standard ports

src/js/background/backgroundLogic.js, src/js/popup.js, test/issues/940.test.js
Fixes https://github.com/mozilla/multi-account-containers/issues/972
I've refactored all anonymous async functions declared using the `function` keyword into arrow-functions.
I understand the crux of this issue isn't to simply replace functions declared using the `function` keyword with arrow-functions, but to inline named async functions where sensible. I've reviewed all named async functions and I believe none would benefit from being inline, with the exception of a few handlers registered using `addListener`. Given the past confusion surrounding this issue, I believe this issue should be closed.
=> Refactor anonymous async functions into arrow-functions

src/js/popup.js
Fix for #1314
1. Load new extension
2. Add groovecoder.com or another site with no favicon to a container and select to always use that container.
3.  Click "Edit containers" and select the container you chose (pencil).
4. default favicon should be displayed.
=> Default favicon now displays for Edit Containers panel (issue #1314)

src/css/popup.css, src/js/popup.js
1. Put MAC addon into the overflow menu (in customize), or shrink Firefox to force it into overflow.
2. Open MAC and click through.
Before:
After:
Full click through for no overflow and then overflow:
=> Fixed #766 — Popup display expands to fit overflow menu

src/css/confirm-page.css
Firefox's dark mode sets the background of the confirmation page to Grey 80 (`#2a2a2e`). As pointed out in [this comment](https://github.com/mozilla/multi-account-containers/issues/1375#issuecomment-500107995), the `#redirect-url` background remains `#efefef`, making the redirect url unreadable. 
This patch corrects the background color in dark mode. It also slightly changes the color in light mode to make it consistent with the [Photon colors](https://design.firefox.com/photon/visuals/color.html).
=> #1375 - Correct colors on confirmation page

src/css/popup.css
#948 Fixes big empty gap above assignments list and multiple scrollbars, when editing container with many assignments.
=> Bugfix: incorrect scrollbars/spacing if edit container with many assignments

src/js/confirm-page.js
Fix for #1361 
from: https://bugzilla.mozilla.org/show_bug.cgi?id=1535643
1. Go to https://www.example.com/path?param=some%2Bvalue in a container
2. Mark it to "Always open in <container>"
3. Open a new tab outside of the container
4. Go to https://www.example.com/path?param=some%2Bvalue
5. Look at the "Open this site in your assigned container?" page
Actual results:
Redirect url is show as "https://www.example.com/path?param=some+value" - notice that "some%2Bvalue" is now "some+value".  Open in <container> button will also open that url and not the original.
Expected results:
Redirect url should show as "https://www.example.com/path?param=some%2Bvalue". Open in <container> button should also open that url.
Repeat above steps. Other urls with special characters still work.
Some other urls …
=> Fix for double decoding on confirm page issue #1361

src/css/confirm-page.css
When using Firefox Multi-Account Containers in KDE Plasma, with a dark theme applied, the `#redirect-url` element contrast is very poor (black-on-black basically):
This tiny PR sets the foreground color (via dark mode media query) to be `#eee`, or slightly-dimmed white:
All tests passed via `npm test`.
=> Explicitly set foreground color of #redirect-url in dark mode

src/js/background/backgroundLogic.js
Add 'noload' property to openNewTab options, add 'discarded' parameter to browser.tabs.create. New tabs will be discarded in case they opened from showTabs
=> Fix #1041- [Feature request] Open previously hidden tabs in the background

src/js/popup.js
Addresses Issues #1009 and #1153 
Added left and right arrow shortcuts for viewing containers in popup browser menu are working. Note that in order to use left arrow, TAB must be pressed to change the focus to the left panel arrow button.
All npm tests passed.
This replaces and completes blocked PR from @tie-rack
Mar 18 2018
https://github.com/mozilla/multi-account-containers/pull/1153#pullrequestreview-291387739
@maxxcrawford 
> This looks great! Can you please add the left key to go back to the main menu when inside a submenu? Happy to take another look after that.
#OutreachyApplicant, first Mozilla containers bug fix
=> added right and left arrow shortcuts for container submenu tabs

src/js/background/backgroundLogic.js, src/js/background/messageHandler.js
fix for https://github.com/mozilla/multi-account-containers/issues/950
Issue: If you open a tab, which was assigned to some containers and you have some hidden tabs from this container at the moment, all the hidden tabs will be opened again. 
Solution: check if the url of the hidden tab was already opened and if so skip it from re-opening to prevent duplicates.
=> #950: don't unhide duplicates of already opened tab

src/js/popup.js
Addresses Issue #1538 
This patch allows user to navigate through onboarding panels (e.g. Get Started) via pressing "return" on the keyboard.
#OutreachyApplicant
=> added keyboard nav to onboarding popups

package.json, src/js/background/backgroundLogic.js, src/manifest.json
Turns out pinned tabs cannot be loaded as `discarded`
1. Pin container tab
2. Hide the container
3. Unhide the container
4. See pinned tab reappear as pinned tab instead of nothing happening
easy peasy
It still opens other (non-pinned) hidden tabs as 'discarded' so they do not load all at once when unhiding.
=> Fix for #1632: Pinned tabs cannot be loaded as 'discarded'

package.json, src/css/popup.css, src/js/popup.js, src/manifest.json, src/popup.html
An Enter key listener was added in a previous PR to allow onboarding keyboard navigation; however, the enter key listener had side effects in other parts of the popup (see #1656 #1643 #1637 ).
I added keyboard navigation by way of tabindex and added focus highlighting as per https://design.firefox.com/photon/components/buttons.html so that the user is notified of the keyboard navigation.
I also bumped the version to 6.2.2.
=> Removed Enter Key Handler (fix for #1656, #1643, and #1637)

src/js/confirm-page.js
Fixes the 'open in current container button' on the confirmation page. It would always default to using the assigned container instead.  
I am not sure what exactly broke it, but [Event.explicitOriginalTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget) is non standard according to MDN. So assigning to separate handlers should be preferable anyway imo.  
I looked into writing test cases for this since according to #1682 this broke before but I could not get the confirmation page working in jsdom.
=> Fixes #1682 'open in current container button' not working

src/js/popup.js
Fixes issue where Facebook container has no icon in popup. Also allows user to select fence icon for other containers.
Fixes https://github.com/mozilla/contain-facebook/issues/491
Relates to https://github.com/mozilla/contain-facebook/issues/205
=> Show fence icon in popup

src/js/popup.js, src/popup.html
Fixes #1785 
Query selector for keyboard nav was wrong. I must have changed that at some point and forgot to test it.
Arrow key nav (up, down, left, right) works on the first and second panels (as I think it did before UI upgrade). Right and left are forward and backward. Broke the listeners out into their own functions to make it more clear what they do.
Tab is still needed to navigate the edit and delete screens (as it was before, and I think makes sense).
I also deleted some stuff that it looks like I commented out last PR, and fixed tab navigation in at least one place.
Steps to test:
Install and try the arrow keys on the container list panel and 1 panel past that.
=> Fixed first panel keyboard arrow nav.  Added second panel keyboard nav.

package.json, src/css/popup.css, src/manifest.json
_Note - This PR also bumps the version number._
Before: 
After:
=> Fixed #1779 - Added CSS override for favicons on the Manage Site List panel

src/css/popup.css, src/js/popup.js, src/js/utils.js, src/popup.html
Expected: 
- Clicking on "Personal" Title/Icon should open new tab in PERSONAL container
- Clicking on ">" should open Personal container subpanel: 
- Using keyboard navigation, arrow down to the Personal container item: 
- On enter, a new tab in PERSONAL container should open
- On right arrow, should open Personal container subpanel:
=> Fixed #1810 - Split container item funcitonality

package.json, src/js/popup.js, src/manifest.json
Fixes #1781 
To verify:
1. Open panel, click "manage containers" 
1. Select first container, check box for Site isolation
1. Click < back button, select other container
1. check box for Site isolation in that container
1. Go back, select first container: 
Expected: Container checkbox is still checked. 
Run through the same test, except instead of going back, click out of panel and reopen/click "manage containers"
=> Site isolation saved changes do not affect other containers

src/js/background/assignManager.js, src/js/options.js, src/options.html, test/common.js
Adds an option in "Preferences" to replace the current tab if a page which is assigned to another container is opened instead of keeping the current tab open. Middle clicking is unaffected and always opens a new tab as before.
Related issues which should be solved by this: #1765 #1704 #1590 #1837
=> Replace tab instead of creating a new one (#1765 #1704 #1590  #1837)

src/css/popup.css
Hi,
As mentioned in #containers:mozilla.org, here's my patch to add a dark mode to MAC. Only the "Limit to designated sites" checkboxes aren't styled since checkbox elements aren't easily styleable without using `appearance: none`. 
Would it be acceptable to merge the patch as is or would you prefer if I also style the checkboxes? If you prefer the latter, we'll need an SVG for the checkbox mark icon.
=> Add a dark mode to MAC

src/css/confirm-page.css
The name is not capitalized in the address bar or the list of names in the extension popup.
For example, one of my containers is "j...n@gmail" for my legacy Google account and it's awkward to see it capitalized as "J...n@gmail" in this single location.
=> Remove automatic capitalization of container name

src/css/popup.css, src/img/container-move.svg, src/js/popup.js
This is just a small patch that makes it possible to move / reorder containers via drag&drop. 
I added a third button next to the edit (pencil) button that allows users to drag a container and insert it before another container. Container positions are saved in the browser's local storage.
I got the icon from the [Mozilla Foundation Icon Font](https://mozilla.github.io/foundation-icons/).
Related issue: #330 
Example:
[firefox_multi-account_containers-6.1.1.zip](https://github.com/mozilla/multi-account-containers/files/4007793/firefox_multi-account_containers-6.1.1.zip)
=> Implement container reordering

README.md
web-ext will not work when following the instructions without having
this diff applied:
```
$ ./node_modules/web-ext/bin/web-ext run -s src/
(node:41062) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41062) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:41062) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:41062) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:41062) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:41062) Warning: Accessing non-existent property …
```
=> Fix development instructions in README

src/js/popup.js
This updates the heading of the "Always Open in" title to be more consistent with the action.
The previous title ("Reopen This Site in") looks like it was copied from the "Reopen Site" panel.
**current behavior**
**updated**
I agree to license this code under the project's open source license (MPL 2.0)
=> Rename 'always open in' title

src/js/background/assignManager.js, src/js/background/backgroundLogic.js, src/js/content-script.js, src/js/popup.js
Replace calls to `browser.extension.getURL()` for `browser.runtime.getURL()`
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getURL
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL
Close #2047
=> Replace deprecated method `browser.extension.getURL()`

src/manifest.json
While looking into [Bug 1720487](https://bugzilla.mozilla.org/show_bug.cgi?id=1720487) I did notice that multi-account-container isn't currently requesting the ["unlimitedStorage" permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#unlimited_storage).
Without the "unlimitedStorage" permission, multi-account-container may more easily hit a quota limit.
Even besides the quota limit, at the moment the QuotaManager data eviction logic does not special case the extension origins and so there is a chance that below certain free disk space threshold the QuotaManager may select an extension origin while looking for the "least used origins to evict data from" (see [Bug 1720487 comment …
=> fix: Add unlimitedStorage permission to make sure storage.local does not hit quota limits or IndexedDB QuotaManager data eviction

src/css/confirm-page.css
Fixes issue #1231 confirmation page alignment
Before:
After:
=> Fixes #1231 confirmation page alignment

src/js/mozillaVpn.js, src/js/popup.js
This implements the last integration-specific string and can be merged ~~after https://github.com/mozilla-l10n/multi-account-containers-l10n/pull/8 has been merged and the 'tooltipWarning' string ID is available~~ now that https://github.com/mozilla-l10n/multi-account-containers-l10n/pull/8 has been merged and the 'tooltipWarning' string ID is available.
=> Add tooltip string

src/js/popup.js
This fixes a bug found whilst preparing product screenshots for Marketing. 
Steps to reproduce: 
1.) Configure a Container to use a Mozilla VPN proxy
2.) Disable the Mozilla VPN proxy configured in Step 1.
3.) Without leaving the "Edit Container" panel, click the "Advanced Proxy Settings" button.
Expected: The Advanced Proxy Settings panel opens
Actual: Nothing happens
=> Fix bug when opening custom proxy panel

src/manifest.json
- Removes the `"applications"` key from manifest.json, which doesn't seem to be a valid key (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json).
- Moves `strict_min_version` to `browser_specific_settings > gecko > strict_min_version` where the AMO linters can find it.
=> Remove nonexistent "applications" manifest key

src/confirm-page.html
Fixes #2214
This is a regression introduced in commit:
05dc48eac2d12dc65dc2e062ad3d64d0fe77051a
The autofocus attribute was removed unexpectedly in a localization
change.
=> Automatically focus confirm button on confirm page

src/js/background/assignManager.js
Happy New Year!
1. Run `web-ext run -s src` on the `main` branch of this repo
1. Assign a proxy to a container
2. Open a tab in that container
3. Visit https://www.dnsleaktest.com
4. Click "Standard Test"
6. Run `web-ext run -s src` on this `proxy-dns-2248` branch of code
7. Assign a proxy to a container
8. Open a tab in that container to https://www.dnsleaktest.com
9. Click "Standard Test"
=> fix #2248: proxy DNS too

src/css/popup.css, src/js/popup.js, src/popup.html
We missed a string in the delete container panel during internationalization. After reviewing this screen, I think we should remove this string altogether and possibly consider implementing something more helpful as a follow-up (perhaps showing the titles of open tabs, pulling relevant tabs into a new window so the user doesn't have to potentially go hunting through their open tabs to find them, something else...), or replacing this with a single generic "Tabs open in this Container will be closed" flag.
Fixes Jira ticket MAC-698
=> Remove delete container warning

src/js/background/mozillaVpnBackground.js
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3128
The reason for this bug is a race - Depending on how fast you open the mac panel between accepting the permission prompt. 
Just after initialization, the extension sends this to the bridge:
```       
this.postToApp("status");
this.postToApp("servers");
```
The response to each is: 
```{ error: "vpn-client-down" }```  
Which will cause the handleResponse to set ```_connected=false``` but leave ```_installed=undefined```. (thus showing the panel)
However as the bridge in the meantime will fail to open a connection to the client it will periodically send for each failed attempt
``` { status: "vpn-client-down" } ```  
Which means we will set ``` installed=true``` the first time the bridge either connects or fails to …
=> Handle any response as signal that the mvpn-bridge is present

src/popup.html
Per my #2295 issue, the UI limits the total proxy input length to 50 characters which is insufficient in the case of credentials or long domain names. This PR simply removes the `maxlength` property completely as there is no upper bound should someone have a very long username and/or password.
=> Remove maxlength from proxy settings

src/js/popup.js
Allows selecting "default container" in "reopen this site in" identity picker using keyboard
=> Make "default container" entry keyboard navigable

src/js/mozillaVpn.js, src/js/popup.js, src/popup.html
This patch currently use the built-in tooltip. The rationale for using the bult-in tooltip is:
* a custom solution is more complexe and time consuming to implement
* it's more important that the warning message is seen by the user than the esthetic of it
* we can re-implement a more robust custom tooltip in a follow-up patch
=> Fix #2377 Tooltip renders off viewport when hovering over a container assigned to VPN.

src/js/background/sync.js, test/features/sync.test.js
Follow-up from https://github.com/mozilla/multi-account-containers/pull/2231.
=> Fix empty regexp and incoming sync exclude behavior

src/css/popup.css, src/js/popup.js, src/popup.html
=> Add ability to filter the container list

src/confirm-page.html, src/js/confirm-page.js
If you assign a website to the Personal container and open the same website in the Work container, it will show you a confirmation page where the left button shows "Open in Work Container". 
However, if the current tab in which you open the website isn't a container, it will show "Open in Container" because the code returns a null value for the container name.
This patch fixes this by showing a different message for this situation by adding a new l10n string (openInNoContainer).
=> Fix #2168 Use a different l10n string for sites opened in no container

src/confirm-page.html
Fixes #2423 
This is a fix for the [regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1794329) introduced by [bug 1734217](https://bugzilla.mozilla.org/show_bug.cgi?id=1734217), as it moved the neterror page files from `browser/` to `toolkit/` in m-c, which results in a path change for the `aboutNetError.css` file that the confirm page depends on.
=> Account for moved aboutNetError.css in Firefox 107

src/js/popup.js
This fix an issue where the user is unable to delete an assignment because the text is overflowing and the delete icon is drawn offcanvas.
=> Fix #2421 - Truncate text to ensure the delete icon is visible

package.json, src/css/popup.css, src/manifest.json
It was impossible to know what color and icon was selected in manage container because the :focus and :active color weren't correctly applied.
=> Fix broken radio focus styling in light mode

package.json, src/confirm-page.html, src/manifest.json
- Account for moved aboutNetError.css in Firefox 107
- Keep both files
- Bump version number for patch release
=> cherry pick bug 1794329

.gitignore, package.json
Add scripts to help dev process
- `dev`: The /src/_locales/.github folder causes `web-ext run` to fail when running the `npm run dev` script. This folder removal isn't tracked or surfaced during local dev work when working from the root directory.
- `build` This script runs `web-ext build`. There was an error when running when running `npm run package` that would call for this missing command. 
- Checkout PR
- Run `$ npm run dev`
- **Expected:** The extension should run locally without any console errors
- Checkout PR
- Run `$ npm run package`
- **Expected:** There should be a new local .zip of the add-on in the `/web-ext-artifacts folder` folder and that file/folder should not be tracked in git. 
- Run `$ git status` to confirm new .zip file is not tracked
=> Add remove/restore scripts for nested .git folder

bin/addons-linter.sh
Tests keep failing bc `$(npm bin)` was not setting the correct path to run an executable. 
See this answer for more info: https://stackoverflow.com/a/15157360
=> Fix failing test install by replacing $(npm bin) with npx

src/js/popup.js
- Add Slash shortcut to focus the filter input
- Use event.code instead of event.keyCode
- Add modifier key detection
=> Add new shortcut navigation in the browser panel

src/js/background/assignManager.js, src/js/background/backgroundLogic.js, src/manifest.json, src/pageActionPopup.html, src/popup.html
This patch fix all the missing i18n strings in the UI. It also standardize the main title to "Firefox Multi-Account Containers" everywhere we use it in the addon.
In `src/js/background/backgroundLogic.js`, we update the i18n strings for the open_container_[0-9] commands on startup and on install. This is done to avoid using both an hardcoded value with a i18n strings (e.g `__MSG_myMessage__ my extra text`). See https://github.com/mozilla-l10n/multi-account-containers-l10n/pull/23
=> Fix missing i18n strings in the UI

.github/ISSUE_TEMPLATE/bug.yml
There's an escape character that breaks our issue template and prevents it to be parsed by Github. This patch removes it.
=> Fix issue template

src/manifest.json
This manifest.json option ensures that the MAC icon is shown in the toolbar after installation. This is needed since the Unified Extension Button has been implemented in Firefox.
=> Add MAC icon in toolbar on install

bin/addons-linter.sh, bin/build-addon.sh, package-lock.json, package.json, src/js/popup.js, src/manifest.json, src/options.html, src/popup.html
- FXA Rebrand 60466258b8d91046ee91bc21df2811506e8afeac
- Bump version number to 8.1.3
Testing steps: (See screenshots for more context)
- Run add-on
- Open panel (Go through onboarding)
- **Expected:** On Syncing panel (Panel 6), there should be no mention of "Firefox"
- Click "Start Syncing"
- **Expected:** On this panel,  there should be no mention of "Firefox"
- Close Panel
- Open MAC Settings page (in `about:addons`)
- **Expected:** The Synchronization section should not mention "Firefox"
=> Firefox Accounts Rebrand (Dot Release) 

bin/addons-linter.sh, bin/build-addon.sh, bin/commons.sh
This enables `npm test` to successfully call scripts in `bin/` with the `bash` binary specified by `PROFILE`.
---
Additional information:
In addition to potentially preferring an alternative version of bash than the one in `/bin/bash`, some distributions forego storing bash in `bin/` at all, such as `NixOS`:
```bash
$ cat /etc/os-release | rg '^NAME=' -r ''
NixOS
$ which bash
/run/current-system/sw/bin/bash
```
* n/a
Related pull requests:
* https://github.com/mozilla/multi-account-containers/commit/83687f63246e93400cc52d1cd6b854c949d40a3b
=> Use `/usr/bin/env` to find bash

src/js/background/assignManager.js
For reference: https://github.com/mozilla-l10n/multi-account-containers-l10n/pull/26
=> Missing translation for a contextmenu item

src/js/popup.js
Since Fx 123, we have a new API (contextualIdentities.move) that let us reorder the container list everywhere in Firefox. This patch looks if the API is supported by the client and propagate the change if it's the case.
* #1958
=> Fix #1958 - Propagate container list reordering in Firefox menus

src/js/background/assignManager.js, src/js/confirm-page.js
When a user is on the confirm-page after re-opening a site they chose to 'always open in a container', if they click "Remember my choice" and then "Open in current tab" (default container), this is not remembered. i.e. The next time they open the site, they are prompted to this screen again. 
This PR fixes that. 
(Remember choice for default container)
* Go to youtube.com
* In the browserAction menu, choose "Always Open This Site in..."
*  Choose the work container
* Open youtube.com in a new tab.
* On the confirmation page prompt, check "Remember my decision for this site" then click "Open in current tab"
* Open youtube.com in a new tab, and verify that there is no confirmation page. (if you want to put it in a container again, click "Always Open …
=> Remember choice for default containers in the "Always open in" confirm page

src/css/popup.css, src/js/background/assignManager.js, src/js/background/backgroundLogic.js, src/js/background/messageHandler.js, src/js/popup.js, src/js/utils.js, src/manifest.json, src/popup.html
Allows users to reset cookies for a site in the containers "Site manager"
1. cd into src/_locales and pull the latest changes. Then checkout the branch titled `clear-storage-confirmation-strings`
2. Go to relay.firefox.com and click the "Always open in container" icon then select your Personal container.
3. Sign in to your Relay account.
4. Open the MAC popup.
5. Click  the right arrow on the "Personal" container, then click "Manage this container"
6. Click on "Manage site list"
7. Verify that you can hover over and see tooltips for the delete and refresh icons.
8. Click on the refresh icon.
9. Verify that the permissions popup shows if you don't have "Clear recent browsing history, cookies, and related data" toggled …
=> #303: Reset cookies in site manager

src/js/background/messageHandler.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1823729#c9
tl;dr If a tab never reach the complete readyState, we can end up in a situation where a frequent (and likely never ending?) sequence of tabs.onUpdated events are triggered. This can create performance issues in a session with a large amount of tabs. By only tracking the onUpdated events we really need, we can considerably reduce the numbers of events and prevent any performance issues.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1823729#c9
* [Bugzilla 1823729](https://bugzilla.mozilla.org/show_bug.cgi?id=1823729)
*
*
=> Fix bz#1823729 - Listen only for status on tab updated

src/js/background/assignManager.js
I was going over the code to look at writing up some PRs and stumbled across 2 small easily corrected issues:
- a Promise’s `resolve()` being called twice, which is meaningless.  
Note that I’ve checked that using else for fallback/function exit is OK per style, see e.g. https://github.com/mozilla/multi-account-containers/blob/60b40a2d9f609572bd55fd59f7206ff4680365ef/src/js/background/assignManager.js#L16-L20
- A function call to `getByContainer()` which doesn’t exist (there is a `getAssignedSites()` which in turn calls `_getByContainer()`)
=> Small fixes

.github/workflows/builds.yaml
The CI build job in my other [PR  ](https://github.com/mozilla/multi-account-containers/pull/2722)fails as it's loading a deprecated GH action, this pr should just fix that, given none of the behavior changes in 
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md apply to this usage. 
=> Update CI actions/upload-artifact to v4

src/js/background/assignManager.js, src/js/background/messageHandler.js, src/js/confirm-page.js, src/js/popup.js, src/js/utils.js
Fixes #2747
Firefox 137 introduced tab groups. Tab group web extension support is rolling out in Firefox 138 and later. Creating a new tab after the last tab in a tab group can inadvertently create the new tab outside of the tab group.
When a user opens a new tab that should be in a container, this patch will make sure that the new tab resides in the same tab group as the original tab.
* #2747
=> Fix #2747: open/reopen container tabs in tab groups when appropriate

src/js/background/backgroundLogic.js, src/manifest.json
Remove suggested keyboard shortcut for the `sort_tabs` operation. For users updating from v8.2.0 of this addon, clear the `sort_tabs` keyboard shortcut if the configured keyboard shortcut is the default suggested key (Ctrl + Comma) from 8.2.0.
A number of users have accidentally pressed Ctrl + Comma and sorted their tabs by container. For some of those users, they did not know what had happened. See some of the following: #1309, #2731
#2492 added Ctrl + Comma as a default shortcut key for sorting tabs by container. This change was released with addon v8.2.0 in Sept 2024.
It is useful to make the sort-tabs-by-container operation accessible by keyboard shortcut, but I think Ctrl + Comma is too close to the main Ctrl + Period shortcut for this addon. I think it's reasonable to make the …
=> Remove suggested key for `sort_tabs`

package.json, src/manifest.json
Firefox Multi-Account Containers 8.3.0
Version 8.2.0 of this add-on configured Ctrl + Comma as the default keyboard shortcut for sorting the tab strip by container. This keyboard shortcut was removed from 8.3.0 in patch #2758. If you use Ctrl + Comma in order to quickly sort tabs by container, then you will need to explicitly reconfigure the keyboard shortcut. https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
- #2753 Avoid sorting tabs in Firefox tab groups
- #2758 Removed suggested keyboard shortcut for tab sorting
- #2722 Removed Mozilla VPN logo banner
- #2572 Fixed add/remove site assignments logic bug
- #2754 Fixed "open/reopen in container" bug that would reopen outside of a Firefox tab group
- #2760 Removed console log spam related to context menu cleanup
- …
=> Version upgrade 8.3.0

.eslintrc.js
CONTRIBUTING.md specifies the minimum supported Firefox version as 91.1.0.
Based on the caniuse.com data for ECMAScript features listed at https://gist.github.com/Julien-Marcou/156b19aea4704e1d2f48adafc6e2acbf, I determined the following minimum Firefox versions that support each ECMAScript version:
- ECMAScript 2018 (current setting) = Firefox 78
- ECMAScript 2019 = Firefox 64
- ECMAScript 2020 = Firefox 80
- ECMAScript 2021 = Firefox 79
- ECMAScript 2022 = Firefox 92
- ECMAScript 2023 = Firefox 104
- ECMAScript 2024 = Firefox 119+ (not exactly sure)
This project is using v7 of eslint which depends on v7 of espree for JavaScript parsing. espree v7 has a maximum ECMAScript support version of ECMAScript 2021.
Based on these findings, increasing the configured `parser.ecmaVersion` from …
=> Increase eslint ecmaVersion to 2021
